---
############################################################################################
# DEBIAN TASKS                                                                             #
############################################################################################

##########################################################################
# Create the service account                                             #
##########################################################################
-
 user:
   groups: adm, cdrom, sudo, dip, plugdev, lpadmin, sambashare
   name: "{{ serviceacct_user }}"
   password: "{{ serviceacct_pass | password_hash('sha512') }}"
   state: present
   update_password: always
   home: /home/sparky
   shell: /bin/bash
   uid: "11111"
 name: "debian | provision CIDSE Ansible service account"
